"""Another migration

Revision ID: 3ef1cae8d3b8
Revises: 097379545e4c
Create Date: 2023-09-28 21:42:04.541695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef1cae8d3b8'
down_revision = '097379545e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
